name: Build binaries

on: [push]

jobs:
  win:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run build
        run: cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: idlerpg-presence-windows
          path: target/release/idlerpg-rich-presence

  osx:
    name: MacOS
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install osxcross
        run: |
          curl -sL https://github.com/natanbc/actions-binaries/releases/download/1/osxcross.tar.gz -o - | tar -xzf -
          sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
          sudo apt update
          sudo apt install libssl1.0.0

      - name: Run build
        run: |
          export PATH="$PATH:$(pwd)/osxcross/bin"
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(pwd)/osxcross/lib"
          export CC="x86_64-apple-darwin15-clang"
          rustup target add x86_64-apple-darwin
          cargo build --release --target=x86_64-apple-darwin

      - uses: actions/upload-artifact@v2
        with:
          name: idlerpg-presence-mac
          path: target/x86_64-apple-darwin/idlerpg-rich-presence

  linux:
    name: Linux
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run build
        run: cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: idlerpg-presence-linux
          path: target/release/idlerpg-rich-presence
