name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rust-src

      - name: Build
        run: |
          cargo build --release --target=x86_64-unknown-linux-gnu
          strip target/x86_64-unknown-linux-gnu/release/idlerpg-rich-presence
          cp target/x86_64-unknown-linux-gnu/release/idlerpg-rich-presence .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: idlerpg-presence-linux
          path: |
            idlerpg-rich-presence

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rust-src

      - name: Build
        run: |
          cargo build --release --target=x86_64-apple-darwin
          strip target/x86_64-apple-darwin/release/idlerpg-rich-presence
          cp target/x86_64-apple-darwin/release/idlerpg-rich-presence .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: idlerpg-presence-macos
          path: |
            idlerpg-rich-presence

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rust-src

      - name: Build
        run: |
          cargo build --release --target=x86_64-pc-windows-msvc
          cp target/x86_64-pc-windows-msvc/release/idlerpg-rich-presence.exe .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: idlerpg-presence-windows
          path: |
            idlerpg-rich-presence.exe
